### ISSUE TITLE
`gaol destroy` without any args "succeeds"

### ISSUE THREAD

**Issue by goonzoid** [contraband/gaol#4]
```
$ gaol destroy
$ echo $?
0
```

Should probably fail if no handle is provided, I would think.

**Comment by xoebus** [comment]
Hmm, I think this is fine. You may have a script that kills all failed Concourse build containers on a loop.

``` bash
while sleep 30; do
  gaol list -p "concourse:exit-status=1" | xargs gaol destroy
done
```

I wouldn't want this to fail if there were no failed containers.

What do you think?

**Comment by goonzoid** [comment]
Yep, you're right. Failure in that case would be a massive par, but not in any way a real or advanced par. Pars of this nature should be avoided.
